language: objective-c
osx_image: xcode8
before_install: gem install cocoapods xcpretty obcd slather -N
after_success: slather
script: set -o pipefail && xcodebuild test -workspace LambdaUI.xcworkspace -scheme LambdaUI -sdk iphonesimulator10.0 | xcpretty
