language: objective-c
osx_image: xcode8
before_install: gem install cocoapods xcpretty obcd slather -N
after_success: slather
script: xcodebuild test -scheme LambdaUI -sdk iphonesimulator10.0 -destination "name=iPhone SE"
